import "./globals.css";
import NavWrapper from "@/components/nav-wrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col min-h-screen mb-48 bg-[#F7F9FD]">
          {children}
        </main>
        <NavWrapper />
      </body>
    </html>
  );
}
