import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col min-h-screen bg-[#F7F9FD]">
          {children}
        </main>
      </body>
    </html>
  );
}
